apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    event: kubecon-eu-2020
    
resources:
- ingress-deployment.yaml
- egress-deployment.yaml
- ingress-service.yaml 
- egress-service.yaml 
- ingress-pdb.yaml
- egress-pdb.yaml
- gateway.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
- virtualservice.yaml 
- bookinfo.yaml