apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway-service-account
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-egressgateway-service-account
  labels:
    app: istio-egressgateway
    istio: egressgateway
