apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    event: kubecon-eu-2020
    
resources:
- gateway.yaml
- virtualservice.yaml
- pdb.yaml
- role.yaml
- rolebinding.yaml
- sa.yaml
- service.yaml 