apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

commonLabels:
  owner: tenant-two

namespace: tenant-two

patchesStrategicMerge:
- deployment.yaml
- service.yaml
- gateway.yaml
  
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ingressgateway-certs
    namespace: tenant-two
    files:
      - secrets/cacert
      - secrets/cert
      - secrets/key
    type: generic