apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    event: kubecon-eu-2020
    
resources:
- deployment.yaml
- gateway.yaml
- pdb.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
- service.yaml 
- virtualservice.yaml 