apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- gateway.yaml
- virtualservice.yaml

commonLabels:
  owner: tenant-two

namespace: tenant-two

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ingressgateway-certs
    namespace: tenant-two
    files:
      - secrets/cacert
      - secrets/cert
      - secrets/key
    type: generic